# yaml-language-server: $schema=https://json.schemastore.org/taskfile.json
---
version: "3"

tasks:
  default:
    desc: Show help
    aliases: [h]
    silent: true
    cmds:
      - task -l --sort alphanumeric

  install:
    desc: install
    aliases: [i]
    run: once
    sources:
      - package.json
      - pnpm-lock.yaml
      - pnpm-workspace.yaml
    cmds:
      - ni
      - pnpm approve-builds

  clean:
    desc: clean
    silent: true
    cmds:
      - rm -rf dist
      - rm -rf coverage

  clean-hard:
    desc: clean hard
    cmds:
      - task: clean
      - rm -rf node_modules/

  run:
    desc: run
    aliases: [r]
    cmds:
      - nlx esno src/index.ts

  watch:
    desc: run (watch mode)
    aliases: [w]
    cmds:
      - nlx esno --watch src/index.ts

  lint:
    desc: Lint
    aliases: [l]
    cmds:
      - pnpm exec biome check --write ./

  type-check:
    desc: type-check
    aliases: [tc]
    ignore_error: true
    cmds:
      - task: install
      - pnpm exec tsc  --noEmit --project ./tsconfig.json

  check:
    desc: Run checks
    cmds:
      - task: type-check
      - task: lint

  lambdas:build:
    desc: Build lambdas
    cmds: 
      - task: install
      - task: clean
      - task: check
      - pnpm exec esbuild --bundle --sourcemap --platform=node --target=node20 lambdas/send-notification.handler.ts --outfile=build/send-notification.handler.js --jsx=automatic --external:'@aws-sdk/*'